#!/usr/bin/php
<?php
/*
@author Shah Newaz Khan 2015
 */
require 'vendor/autoload.php';
 
use Parse\ParseClient;
 
ParseClient::initialize('HymbXJIgdgKl7i45sEXi29BsAvMXwomlkDgH2TC8', '7VzTNhgct7QqwGNzbjw19ngY9Fp1wPcW3fByj0UG', 'nmzlXi5Ejm9JDfPFC01a3yvLXqGoO6NGtAgjDbie');

use Parse\ParseObject;


//Parse arguments
foreach ($argv as $arg) 
{
    if( strcmp($arg, "-v") == 0 ) getVersion();
    if( strcmp($arg, "init") == 0 ) initParse();

}

function getVersion()
{
	echo "Beta Version 0.1" . "\n" ;
}

function initParse()
{
	$gameScore = new ParseObject("GameScore");
 
	$gameScore->set("score", 1337);
	$gameScore->set("playerName", "Sean Plott");
	$gameScore->set("cheatMode", false);
	 
	try {
	  //$gameScore->save();
	  echo 'New object created with objectId: ' . $gameScore->getObjectId();
	} catch (ParseException $ex) {  
	  // Execute any logic that should take place if the save fails.
	  // error is a ParseException object with an error code and message.
	  echo 'Failed to create new object, with error message: ' + $ex->getMessage();
	}
}