#!/usr/bin/php
<?php
/*
@author Shah Newaz Khan 2015
 */
require 'vendor/autoload.php';
include 'vendor/phpqrcode/qrlib.php';
 
use Parse\ParseClient;
 
ParseClient::initialize('HymbXJIgdgKl7i45sEXi29BsAvMXwomlkDgH2TC8', '7VzTNhgct7QqwGNzbjw19ngY9Fp1wPcW3fByj0UG', 'nmzlXi5Ejm9JDfPFC01a3yvLXqGoO6NGtAgjDbie');

use Parse\ParseObject;
use Parse\ParseQuery;


//Parse arguments
foreach ($argv as $arg) 
{
    if( strcmp($arg, "-v") == 0 ) getVersion();
    if( strcmp($arg, "-b") == 0) whoseOnBranch($argv);
}

function getVersion()
{
	echo "Beta Version 0.2" . "\n" ;
}

function whoseOnBranch($argv)
{
	$fc = explode("\n", file_get_contents( getcwd() . "/.git/config" , true));
	
	for ($i=0; $i < count($fc); $i++)
		if (strpos($fc[$i],'remote') !== false)
			if(strpos($fc[$i + 1], 'url') !== false)
				$remote = explode(" ",$fc[$i + 1]);

	exec('git rev-parse --abbrev-ref HEAD > .currentBranch.txt');
	$branch = explode("\n", file_get_contents( getcwd() . "/.currentBranch.txt" , true));
	exec('rm .currentBranch.txt');

	exec('git config user.user > .currentUser.txt');
	$user = explode("\n", file_get_contents( getcwd() . "/.currentUser.txt" , true));
	exec('rm .currentUser.txt');	

	QRcode::png($remote[2], 'iamon.png'); 	
	
	$query = new ParseQuery("Project");
	$query->equalTo("remote", $remote[2]);
	$query->equalTo("branch", $argv[2]);

	$results = $query->find();

	foreach ($results as $result)
	{
		echo "User: " . $result->get('user') . " is on branch: " . $result->get('branch') . "\n";
	}

}